import { Sidebar } from '@/components/sidebar';
import { TooltipProvider } from '@/components/tooltip';
import { TopNav } from '@/components/top-nav';
import { Provider } from '@/provider';
import '@/styles/globals.css';
import { type Metadata, type Viewport } from 'next';
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
  },
  colorScheme: 'light dark',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#F7F9FB' },
    { media: '(prefers-color-scheme: dark)', color: '#0B0F19' },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="bg-background-light dark:bg-background-dark"
    >
      <head>
        <style
          dangerouslySetInnerHTML={{
            __html: `
              html, body { background-color: #F7F9FB; }
              @media (prefers-color-scheme: dark) {
                html, body { background-color: #0B0F19; }
              }
            `,
          }}
        />
      </head>
      <body className="font-display bg-background-light dark:bg-background-dark text-gray-800 dark:text-gray-100 min-h-[100dvh] transition-colors duration-300 relative overflow-x-hidden">
        <NextTopLoader showSpinner={false} color="#ff014e" />
        <Provider>
          <TooltipProvider delayDuration={0}>
            <div className="flex min-h-[100dvh]">
              <Sidebar />
<div className="flex-1 flex flex-col safe-area-top lg:pt-0">                <TopNav />
                <div className="container mx-auto max-w-7xl px-4 py-6 md:p-6">
                  <main className="w-full">{children}</main>
                </div>
              </div>
            </div>
          </TooltipProvider>
          <Toaster richColors position="top-center" closeButton />
        </Provider>
      </body>
    </html>
  );
}
