import { Sidebar } from '@/components/sidebar';
import { TooltipProvider } from '@/components/tooltip';
import { TopNav } from '@/components/top-nav';
import { Provider } from '@/provider';
import '@/styles/globals.css';
import { type Metadata } from 'next';
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className="font-display bg-background-light dark:bg-background-dark text-gray-800 dark:text-gray-100 min-h-screen transition-colors duration-300 relative overflow-x-hidden"
      >
        <NextTopLoader showSpinner={false} color="#ff014e" />
        <Provider>
          <TooltipProvider delayDuration={0}>
            <div className="flex min-h-screen">
              <Sidebar />
              <div className="flex-1">
                <TopNav />
                <div className="container mx-auto max-w-7xl p-6">
                  <main className="w-full">{children}</main>
                </div>
              </div>
            </div>
          </TooltipProvider>
          <Toaster richColors position="top-center" closeButton />
        </Provider>
      </body>
    </html>
  );
}
