import { Provider } from "@/provider";
import "@/styles/globals.css";
import { type Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
import { ThemeProvider } from "@/components/theme-provider";
import { Sidebar } from "@/components/sidebar";
import { TopNav } from "@/components/top-nav";
import { TooltipProvider } from "@/components/tooltip";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className}`} suppressHydrationWarning>
      <body>
        <NextTopLoader showSpinner={false} color="#ff014e" />
        <Provider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {/* <SettingsProvider> */}
            <TooltipProvider delayDuration={0}>
              <div className="flex min-h-screen">
                <Sidebar />
                <div className="flex-1">
                  <TopNav />
                  <div className="container mx-auto max-w-7xl p-6">
                    <main className="w-full">{children}</main>
                  </div>
                </div>
              </div>
            </TooltipProvider>
            {/* </SettingsProvider> */}
          </ThemeProvider>
          <Toaster richColors position="top-center" closeButton />
        </Provider>
      </body>
    </html>
  );
}
