import { Provider } from "@/provider";
import "@/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"  className={`${geist.variable}`} suppressHydrationWarning>
      <body>
        <NextTopLoader showSpinner={false} color="#ff014e" />
        <Provider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <SettingsProvider>
              <TooltipProvider delayDuration={0}>
                <div className="flex min-h-screen">
                  <Sidebar />
                  <div className="flex-1">
                    <TopNav />
                    <div className="container mx-auto max-w-7xl p-6">
                      <main className="w-full">{children}</main>
                    </div>
                  </div>
                </div>
              </TooltipProvider>
            </SettingsProvider>
          </ThemeProvider>
          <Toaster richColors position="top-center" closeButton />
        </Provider>
      </body>
    </html>
  );
}
